server:
  port: 8761
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
  client:
    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: discover-eureka-server
logging:
  file: /Volumes/DYZ-document/Program/X-CodeRunSpace/log/discoverservice/discover-eureka.log